# Zurg configuration version (default: "v1")
zurg: v1

# Your Real-Debrid API token (required)
token: *****

# Host address to bind to (default: "[::]")
host: "[::]"
# port: 9999
# username:
# password:
# proxy:

# Retry 503 errors specifically
retry_503_errors: false

# Enable automatic torrent repair
enable_repair: true

# How often to check for changes in the library (default: 15 seconds)
check_for_changes_every_secs: 10

# Will ignore rename values in the torrent
ignore_renames: true

# Retain the name value of a torrent from real-debrid (if false, will use original_name instead)
retain_rd_torrent_name: true

# Retain the torrent name extension which is used for directory names (useful for single file torrents)
retain_folder_name_extension: true

# Enable debug log level
log_level: debug
